name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run workflow when pushing to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      # Uncomment to run tests
      # - name: Run tests
      #   run: npm test

  deploy:
    needs: build-and-test  # Run deploy after build-and-test completes successfully
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Build project
        run: npm run build

      - name: Deploy to Server via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          # Save SSH private key to file and set correct permissions
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          
          # Disable pseudo-terminal allocation and deploy to the server with verbose logging
          ssh -v -T -o StrictHostKeyChecking=no -i private_key -p 2002 $SSH_USER@$SERVER_IP << 'EOF'
            cd /home/gomes/app
            git pull origin main
            npm install
            #npm run build
            pm2 start server.js
          EOF

          # Clean up the private key file for security reasons
          rm -f private_key
